[project]
name = "T2L"
version = "1.1.0"
description = "L2T - a Language to Translate"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pypdf2>=3.0.1",
    "torch>=2.7.0",
    "transformers>=4.51.3",
]
